spring:
  application:
    name: springboot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://106.14.157.213:3306/springboot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Dinghaiting19980501@
    driver-class-name: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    root: info
#    com.zimug.boot.launch.controller: debug
#  file:
#    path: D:\logs
#    name: D:\logs\boot-launch.log
#    max-size: 10MB
#    max-history: 10
#  pattern:
#    console: '%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'
#    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger : %msg%n'