# \u683C\u5F0F\u5316\u5168\u5C40\u65F6\u95F4\u5B57\u6BB5
spring:
  application:
    name: springboot
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    # \u6307\u5B9A\u65F6\u95F4\u533A\u57DF\u7C7B\u578B
    time-zone: GMT+8
  datasource:
    primary:
      url: jdbc:mysql://106.14.157.213:3306/springboot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Dinghaiting19980501@
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://106.14.157.213:3306/springboot1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Dinghaiting19980501@
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: validate
      database: mysql
      show-sql: true

  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        max-pool-size: 20
        borrow-connection-timeout: 60
#  max-pool-size\u8868\u793A\u6570\u636E\u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF0C\u8BF7\u6839\u636E\u81EA\u5DF1\u7684\u5E94\u7528\u89C4\u6A21\u8FDB\u884C\u8C03\u6574
#  borrow-connection-timeout\u8868\u793A\u8FDE\u63A5\u4ECE\u8FDE\u63A5\u6C60\u201C\u501F\u51FA\u201D\u4E4B\u540E\u7684\u8D85\u65F6\u65F6\u95F4\uFF0C\u8D85\u65F6\u5C06\u629B\u51FA\u5F02\u5E38